version: '3.8'

services:
  mirrorly-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: mirrorly-api-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    networks:
      - mirrorly-network
    depends_on:
      - mysql
      - redis
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: mirrorly-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
      MYSQL_DATABASE: mirrorly_dev
      MYSQL_USER: mirrorly_dev
      MYSQL_PASSWORD: dev_password
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    networks:
      - mirrorly-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: mirrorly-redis-dev
    restart: unless-stopped
    command: redis-server --requirepass dev_password
    volumes:
      - redis_dev_data:/data
    ports:
      - "7380:6379"  # Different port to avoid conflicts
    networks:
      - mirrorly-network

  adminer:
    image: adminer
    container_name: mirrorly-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - mirrorly-network
    depends_on:
      - mysql

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: mirrorly-redis-commander-dev
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:1:dev_password
    ports:
      - "8081:8081"
    networks:
      - mirrorly-network
    depends_on:
      - redis

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  mirrorly-network:
    driver: bridge